# Generated by Django 6.0.6 on 2026-07-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_announcement_alter_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('document_type', models.CharField(choices=[('Resume', 'Resume'), ('ID Proof', 'ID Proof'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
